version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestSoapProject
  gitServerName: git
  gitUrl: https://github.com/Vijaya-Dodamani-IBM
  gitUsername: Vijaya-Dodamani-IBM
  gitBranch: main
services:
- serviceName: project.testsoap.soap.connections:TestGitSoap
  packages:
  - name: TestSoapProject
    version: "1.0"
- serviceName: project.testsoap.soap.connectors.TestNC_.connectors:NumberConversionSoapType_NumberToDollars
  packages:
  - name: TestSoapProject
    version: "1.0"
- serviceName: pub.client:soapClient
  packages:
  - name: WmPublic
    version: 12.1.0.0.836
- serviceName: project.testsoap.soap.connectors.TestNC_.connectors:NumberConversionSoapType_NumberToWords
  packages:
  - name: TestSoapProject
    version: "1.0"
- serviceName: project.testsoap.soap.connectors.TestNC_.responseServices:NumberConversionSoapType_NumberToDollars_Response
  packages:
  - name: TestSoapProject
    version: "1.0"
- serviceName: project.testsoap.soap.connectors.TestNC_.responseServices:NumberConversionSoapType_NumberToWords_Response
  packages:
  - name: TestSoapProject
    version: "1.0"
- serviceName: project.testsoap.soap.connectors.TestNC_.responseServices:genericFault_Response
  packages:
  - name: TestSoapProject
    version: "1.0"
